title: CriticalMAAS AIM 
description: A Machine Learning Model to Discover Critical Minerals from Maps
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme